--------------------------------------------------------------------------------
-- HYPRLAND MASTER CONFIGURATION ENTRY POINT
--------------------------------------------------------------------------------

-- Disable the autogenerated warning banner at startup
hl.config({ autogenerated = false })

-- Load default choices and applications first
-- This establishes your configuration tables so the other files can read them
require("config.defaults")

-- Load core environment and backend parameters
require("config.environment")

-- Load look, feel, animations, and monitor profiles
require("config.monitors")
require("config.look_feel")

-- Load inputs, touchpads, and gestures
require("config.input")

-- Load core keybindings, window rules, and permissions
require("config.keybindings")
require("config.permissions")
require("config.windows_workspaces")

-- Launch autostart apps and scripts last
require("config.autostart")
