preload = /home/dylan/Pictures/Hyprpapers/cyberpunk-visionary-science-fiction-futuristic.jpg
wallpaper = ,/home/dylan/Pictures/Hyprpapers/cyberpunk-visionary-science-fiction-futuristic.jpg
ipc = true
