preload = /home/dylan/Pictures/Hyprpapers/digital-digital-art-artwork-illustration-abstract-hd-wallpaper.jpg
wallpaper = ,/home/dylan/Pictures/Hyprpapers/digital-digital-art-artwork-illustration-abstract-hd-wallpaper.jpg
ipc = true
