preload = /home/dylan/Pictures/Hyprpapers/digital-art-artwork-cyberpunk-science-fiction-city-hd-wallpaper.jpg
wallpaper = ,/home/dylan/Pictures/Hyprpapers/digital-art-artwork-cyberpunk-science-fiction-city-hd-wallpaper.jpg
ipc = true
